FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

WORKDIR /app

# =========================
# PYTHON + SYSTEM DEPS
# =========================

RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    wget \
    git \
    unzip \
    xvfb \
    python3 \
    python3-pip \
    python3-venv \
    ca-certificates \
    fonts-liberation \
    fonts-freefont-ttf \
    fonts-noto-color-emoji \
    fonts-ipafont-gothic \
    fonts-wqy-zenhei \
    fonts-thai-tlwg \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libegl1 \
    libenchant-2-2 \
    libepoxy0 \
    libevent-2.1-7 \
    libfontconfig1 \
    libgbm1 \
    libgdk-pixbuf-2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libgtk-4-1 \
    libgstreamer-gl1.0-0 \
    libgstreamer-plugins-base1.0-0 \
    libgstreamer1.0-0 \
    libharfbuzz-icu0 \
    libharfbuzz0b \
    libhyphen0 \
    libicu70 \
    libjpeg-turbo8 \
    liblcms2-2 \
    libmanette-0.2-0 \
    libnotify4 \
    libnspr4 \
    libnss3 \
    libopenjp2-7 \
    libopus0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpng16-16 \
    libsecret-1-0 \
    libwayland-client0 \
    libwayland-egl1 \
    libwayland-server0 \
    libwebpdemux2 \
    libwoff1 \
    libx11-6 \
    libx11-xcb1 \
    libxcb-shm0 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxkbcommon0 \
    libxrandr2 \
    libxrender1 \
    libxshmfence1 \
    libxss1 \
    libxtst6 \
    xdg-utils \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

    
FROM python:3.13-slim

WORKDIR /app

RUN python3.13 -m pip install pip --upgrade

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates git
RUN apt-get update -y
RUN apt-get install -y gdal-bin

# special lib for playwright
RUN pip install --no-cache-dir playwright==1.57.0
RUN python -m playwright install --with-deps chromium

# =========================
# VERIFY
# =========================

RUN python3 -c "from playwright.sync_api import sync_playwright; \
with sync_playwright() as p: \
    browser = p.chromium.launch(headless=True,args=['--no-sandbox']); \
    print(browser.version); \
    browser.close()"

# =========================
# COPY APP
# =========================

COPY . .

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]