[phases.setup]
nixPkgs = [
  "glib",
  "nspr",
  "nss",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "libdrm",
  "gtk3",
  "expat",
  "xcb-util",
  "libxkbcommon",
  "pango",
  "cairo",
  "alsa-lib"
]